// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string;

/**
 * Dynamic headers that get injected into every Supabase REST/RPC request.
 * Used to pass the Clerk user ID so PostgreSQL RLS functions can identify the user.
 */
export const dynamicHeaders: Record<string, string> = {};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: (url: RequestInfo | URL, options?: RequestInit) => {
      const headers = new Headers(options?.headers);
      for (const [key, value] of Object.entries(dynamicHeaders)) {
        if (value) headers.set(key, value);
      }
      return fetch(url, { ...options, headers });
    },
  },
});
